[package]
name = "rust_data_analyze"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = { version = "0.48", features = ["lazy"] }
plotters = "0.3"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
